# Cell Types
WALKABLE_CELL = 'G'
OUT_OF_BOUNDS_CELL = 'R'
MOUNTAIN_CELL = 'O'
FOOD_CELL = 'F'
PLAYER_CELL = 'W'

# Screen dimensions
WIDTH, HEIGHT = 800, 800
ROWS, COLS = 40, 40
CELL_SIZE = WIDTH // COLS

# Define colors
GREEN = (0, 255, 0)
RED = (255, 0, 0)
ORANGE = (255, 165, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

COLOR_MAP = {
    WALKABLE_CELL: GREEN,
    OUT_OF_BOUNDS_CELL: BLACK,
    MOUNTAIN_CELL: RED,
    FOOD_CELL: BLUE,
    PLAYER_CELL: WHITE
}
